# Generated by Django 2.0.7 on 2018-07-24 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=64, verbose_name='Exam_name')),
                ('logo', models.ImageField(null=True, upload_to='logos')),
                ('description', models.CharField(default=' ', max_length=600, verbose_name='Exam_descr')),
                ('timer', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Free_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(default=' ', max_length=600, verbose_name="header's text")),
            ],
        ),
        migrations.CreateModel(
            name='MultiChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_variant', models.CharField(default=' ', max_length=600, verbose_name="header's text")),
                ('multi_description', models.CharField(default=' ', max_length=600, verbose_name="header's text")),
                ('choice_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='One_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_variant', models.CharField(default=' ', max_length=600, verbose_name="header's text")),
                ('answer_description', models.CharField(default=' ', max_length=600, verbose_name="header's text")),
                ('answer_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default=' ', max_length=256, verbose_name="Question's text")),
                ('point', models.IntegerField(default=0)),
                ('header_text', models.CharField(default=' ', max_length=600, verbose_name="header's text")),
                ('footer_text', models.CharField(default=' ', max_length=600, verbose_name="footer's text")),
                ('success_message', models.CharField(default=' ', max_length=600, verbose_name="success's message")),
                ('fail_message', models.CharField(default=' ', max_length=600, verbose_name="fail's message")),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.Exam')),
            ],
        ),
        migrations.AddField(
            model_name='one_answer',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='multichoice',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='free_text',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FreeText', to='quiz.Question'),
        ),
    ]
