# Generated by Django 2.0.7 on 2018-07-30 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0003_auto_20180730_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='free_text',
            old_name='quest',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='multichoice',
            old_name='quest',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='one_answer',
            old_name='quest',
            new_name='question',
        ),
    ]
