# Generated by Django 2.0.7 on 2018-07-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0005_auto_20180730_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.CharField(default=' ', max_length=200, verbose_name='category'),
        ),
    ]
