# Generated by Django 2.0.7 on 2018-08-06 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0007_reponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='multichoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='multi_choice_answer', to='quiz.MultiChoice'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='one_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='One_answer',
                                    to='quiz.One_answer'),
        ),
    ]
