# Generated by Django 2.0.7 on 2018-08-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0008_auto_20180806_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
