# Generated by Django 2.0.7 on 2018-08-08 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0009_exam_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='score',
        ),
    ]
